name: 'Publish Maven Central Staging'

on:
  push:
    tags:
      - '*'

env:
  GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
  GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
  SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  ci:
    uses: ./.github/workflows/test-lib.yml

  publish:
    runs-on: macos-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish to Sonatype Staging
        run: ./gradlew publishAggregationToCentralPortal -PGPG_SIGNING_REQUIRED

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
